### ISSUE TITLE
Blazegraph fails to start, provides no log output at all

### ISSUE THREAD

**Issue by lyrixderaven** [GRIDAPPSD/gridappsd-docker#56]
Having followed the instructions, the `run.sh` script originally pulled version tag `v2022.08.0` for all containers without problems, and also brought them up, but fails at the `Getting blazegraph status` step:

```
Getting blazegraph status
Error contacting http://localhost:8889/bigdata/namespace/kb/ (000)
Exiting
```

I have confirmed that the container is properly publishing port `8999` on the host; the java process inside the container is up and running, but also seems to incur 100% CPU load. The `docker compose logs blazegraph` output is empty. 

Checking the docker hub versions, I found that the latest version tag seems to be `v2023.05.0`, which i then tried for the whole stack via `./run.sh  -t v2023.05.0` as well, to no avail.

Next I've tried to force debug output from jetty by overwriting the startup command in the `docker-compose.yml` file:

```
  blazegraph:
    image: gridappsd/blazegraph${GRIDAPPSD_TAG}
    container_name: blazegraph
    ports:
      - 8889:8080
    command: "java -Xmx1g -Xdebug -Dorg.eclipse.jetty.util.log.class=org.eclipse.jetty.util.log.StdErrLog -Dorg.eclipse.jetty.server.LEVEL=DEBUG -Dcom.bigdata.rdf.sail.webapp.ConfigParams.propertyFile=/RWStore.properties -jar /usr/local/jetty/start.jar"
```

This gives, at least, minimal log output:

```
2023-07-31 13:36:34 2023-07-31 11:36:34.000:INFO:docker-entrypoint:jetty start from /var/lib/jetty/jetty.start
2023-07-31 13:42:09 2023-07-31 11:42:09.000:INFO:docker-entrypoint:jetty start from /var/lib/jetty/jetty.start
```

But it still doesn't seem like the jetty process is coming up properly; there does not seem to be any process listening on the internal `:8080` port as well. Using the `-d` debug switch with `run.sh` didn't help either, as it just shows the 60 timed out attempts to reach port `8999` on the container.

Is there any way I can force the jetty container to spit out debug information during startup so I can figure out why it won't start the blazegraph instance? Or is there something else I might try?
